spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:mariadb://localhost:3307/identity_service
    driverClassName: "org.mariadb.jdbc.Driver"
    password: root
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
  servlet:
    context-path: /identity
